/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.akamsa.view.ui;

import com.mycompany.akamsa.common.ClickListener;
import com.mycompany.akamsa.view.CategoryDashboardView;

/**
 *
 * @author ASUS
 */
public class CategoryDashboardUi extends javax.swing.JFrame implements CategoryDashboardView {

    /**
     * Creates new form nitip
     */
    public CategoryDashboardUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        toolButton = new javax.swing.JButton();
        carrierButton = new javax.swing.JButton();
        navigationButton = new javax.swing.JButton();
        tendaButton = new javax.swing.JButton();
        wearsButton = new javax.swing.JButton();
        lightingButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnHomePage = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnSewa = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnTransaksi2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(240, 247, 247));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("Kategori");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 38, -1, -1));

        toolButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/KiteriaPeralatan.jpg"))); // NOI18N
        toolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolButtonActionPerformed(evt);
            }
        });
        jPanel3.add(toolButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 225, 225));

        carrierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/KriteriaCarrie.jpg"))); // NOI18N
        carrierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrierButtonActionPerformed(evt);
            }
        });
        jPanel3.add(carrierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 225, 225));

        navigationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/KriteriaNavigasi.jpg"))); // NOI18N
        navigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigationButtonActionPerformed(evt);
            }
        });
        jPanel3.add(navigationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 225, 225));

        tendaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/KriteriaTenda.jpg"))); // NOI18N
        tendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tendaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(tendaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 225, 225));

        wearsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/KriteriaWears.jpg"))); // NOI18N
        wearsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wearsButtonActionPerformed(evt);
            }
        });
        jPanel3.add(wearsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 225, 225));

        lightingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/KriteriaPencahayaan.jpg"))); // NOI18N
        lightingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightingButtonActionPerformed(evt);
            }
        });
        jPanel3.add(lightingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 225, 225));

        jPanel2.setBackground(new java.awt.Color(5, 54, 44));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoBig.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Akamsa");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        btnHomePage.setBackground(new java.awt.Color(5, 54, 44));
        btnHomePage.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnHomePage.setText("Home Page");
        jPanel2.add(btnHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 40));

        btnTransaksi.setBackground(new java.awt.Color(5, 54, 44));
        btnTransaksi.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnTransaksi.setText("Purchase Cart");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel2.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 40));

        btnSewa.setBackground(new java.awt.Color(5, 54, 44));
        btnSewa.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnSewa.setText("Sewa");
        btnSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSewaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 40));

        btnLogOut.setBackground(new java.awt.Color(5, 54, 44));
        btnLogOut.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 200, 40));

        btnTransaksi2.setBackground(new java.awt.Color(5, 54, 44));
        btnTransaksi2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnTransaksi2.setText("Transaksi");
        btnTransaksi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksi2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnTransaksi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toolButtonActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSewaActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnTransaksi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaksi2ActionPerformed

    private void carrierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrierButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carrierButtonActionPerformed

    private void navigationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navigationButtonActionPerformed

    private void tendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tendaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tendaButtonActionPerformed

    private void wearsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wearsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wearsButtonActionPerformed

    private void lightingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryDashboardUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryDashboardUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryDashboardUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryDashboardUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CategoryDashboardUi ui = new CategoryDashboardUi();
                ui.setLocationRelativeTo(null);
                ui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomePage;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSewa;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnTransaksi2;
    private javax.swing.JButton carrierButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton lightingButton;
    private javax.swing.JButton navigationButton;
    private javax.swing.JButton tendaButton;
    private javax.swing.JButton toolButton;
    private javax.swing.JButton wearsButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addLightingListener(ClickListener listener) {
        this.lightingButton.addActionListener(e -> listener.onClick());
    }

    @Override
    public void addTendaListener(ClickListener listener) {
        this.tendaButton.addActionListener(e -> listener.onClick());
    }

    @Override
    public void addToolListener(ClickListener listener) {
        this.toolButton.addActionListener(e -> listener.onClick());
    }

    @Override
    public void addWearListener(ClickListener listener) {
        this.wearsButton.addActionListener(e -> listener.onClick());
    }

    @Override
    public void addCarrierListener(ClickListener listener) {
        this.carrierButton.addActionListener(e -> listener.onClick());
    }

    @Override
    public void addNavigationListener(ClickListener listener) {
        this.navigationButton.addActionListener(e -> listener.onClick());
    }

    @Override
    public void open() {
        this.setVisible(true);
    }

    @Override
    public void close() {
        this.dispose();
    }
}
